-- Initial database schema for Skafferiet (Recipe & Pantry Sync)

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    instructions TEXT,
    servings INTEGER,
    prep_time_minutes INTEGER,
    cook_time_minutes INTEGER,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    category VARCHAR(50) NOT NULL DEFAULT 'PANTRY'
);

CREATE TABLE recipe_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id BIGINT NOT NULL,
    ingredient_id BIGINT NOT NULL,
    amount DOUBLE PRECISION,
    unit VARCHAR(50),
    notes VARCHAR(255),
    CONSTRAINT fk_recipe_ingredients_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE,
    CONSTRAINT fk_recipe_ingredients_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

CREATE TABLE pantry_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT NOT NULL UNIQUE,
    quantity DOUBLE PRECISION,
    unit VARCHAR(50),
    quantity_level VARCHAR(50),
    in_stock BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_pantry_items_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
);

CREATE INDEX idx_recipe_ingredients_recipe ON recipe_ingredients(recipe_id);
CREATE INDEX idx_recipe_ingredients_ingredient ON recipe_ingredients(ingredient_id);
CREATE INDEX idx_pantry_items_ingredient ON pantry_items(ingredient_id);
