-- Add meal plans table for weekly meal planning

CREATE TABLE meal_plan_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_date DATE NOT NULL,
    meal_type VARCHAR(50) NOT NULL,
    recipe_id BIGINT,
    custom_title VARCHAR(255),
    servings INTEGER NOT NULL DEFAULT 4,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_meal_plan_items_recipe FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE SET NULL
);

CREATE INDEX idx_meal_plan_items_date ON meal_plan_items(plan_date);
CREATE INDEX idx_meal_plan_items_recipe ON meal_plan_items(recipe_id);
