-- Add shopping list items table for synchronized shopping list

CREATE TABLE shopping_list_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_id BIGINT,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT 'OTHER',
    amount DOUBLE PRECISION,
    unit VARCHAR(50),
    checked BOOLEAN NOT NULL DEFAULT FALSE,
    recipe_title VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_shopping_list_ingredient FOREIGN KEY (ingredient_id) REFERENCES ingredients(id) ON DELETE SET NULL
);

CREATE INDEX idx_shopping_list_checked ON shopping_list_items(checked);
CREATE INDEX idx_shopping_list_ingredient ON shopping_list_items(ingredient_id);
